name: release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: build_to_release
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    
    - name: Fetch tags
      run: |
        git fetch --prune --unshallow --tags

    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Make plik release
      run: make release

    - name: Upload artifacts to release
      uses: softprops/action-gh-release@v1
      with:
        files: releases/*
